# Generated by Django 5.2.7 on 2025-10-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_alter_director_age_alter_rating_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre_en',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre_ky',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre_ru',
        ),
        migrations.AddField(
            model_name='actor',
            name='actor_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='actor_name_ky',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='actor_name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='director_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='director_name_ky',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='director_name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='status_movie_en',
            field=models.CharField(choices=[('pro', 'pro'), ('simple', 'simple')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='status_movie_ky',
            field=models.CharField(choices=[('pro', 'pro'), ('simple', 'simple')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='status_movie_ru',
            field=models.CharField(choices=[('pro', 'pro'), ('simple', 'simple')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='types_en',
            field=models.CharField(choices=[('140p', '140p'), ('360p', '360p'), ('480p', '480p'), ('720p', '720p'), ('1080p', '1080p')], default='480p', max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='types_ky',
            field=models.CharField(choices=[('140p', '140p'), ('360p', '360p'), ('480p', '480p'), ('720p', '720p'), ('1080p', '1080p')], default='480p', max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='types_ru',
            field=models.CharField(choices=[('140p', '140p'), ('360p', '360p'), ('480p', '480p'), ('720p', '720p'), ('1080p', '1080p')], default='480p', max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='movielanguages',
            name='language_en',
            field=models.CharField(max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='movielanguages',
            name='language_ky',
            field=models.CharField(max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='movielanguages',
            name='language_ru',
            field=models.CharField(max_length=42, null=True),
        ),
    ]
