# Generated by Django 5.2.7 on 2025-11-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_alter_movielanguages_movie_alter_rating_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='status_movie',
            field=models.CharField(choices=[('pro', 'pro'), ('simple', 'simple')], default='simple', max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status_movie_en',
            field=models.CharField(choices=[('pro', 'pro'), ('simple', 'simple')], default='simple', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status_movie_ky',
            field=models.CharField(choices=[('pro', 'pro'), ('simple', 'simple')], default='simple', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status_movie_ru',
            field=models.CharField(choices=[('pro', 'pro'), ('simple', 'simple')], default='simple', max_length=10, null=True),
        ),
    ]
