# Generated by Django 5.2.7 on 2025-11-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_rating_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(related_name='movies_director', to='movie_app.director'),
        ),
    ]
