# Generated by Django 5.2.7 on 2025-11-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0007_alter_movie_actor_alter_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.ManyToManyField(related_name='countries', to='movie_app.country'),
        ),
    ]
