# Generated by Django 5.2.7 on 2025-11-05 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_rating_parent_alter_movielanguages_movie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(related_name='movies_director', to='movie_app.director'),
        ),
    ]
